version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: webpack
    versions:
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: cypress
    versions:
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
  - dependency-name: node-abort-controller
    versions:
    - 1.2.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: concurrently
    versions:
    - 6.0.1
  - dependency-name: typedoc
    versions:
    - 0.20.35
  - dependency-name: "@opentelemetry/plugin-http"
    versions:
    - 0.18.1
  - dependency-name: next
    versions:
    - 10.0.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@opentelemetry/core"
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
  - dependency-name: "@opentelemetry/tracing"
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
  - dependency-name: "@opentelemetry/api"
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
  - dependency-name: "@opentelemetry/web"
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
  - dependency-name: "@opentelemetry/node"
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
    - 0.18.0
